[+] Update.
Polar-Pumpkin/ParrotX pull request #7
Opened 2021-02-07 07:44 UTC by Micalhl

本次 Commit 共包含以下内容:
- 现在, 你可以一键在 bStats 关联自己的插件了. (试运行)
  你需要在 config.yml 的 PluginID 设置为你的 ID.
- 自动加载器新增 BaseExpansion.
- 代码写得不好, 凑合看吧(bushi).

2021-02-07 07:50 UTC, Micalhl commented
打了个大大的×，Codacy Static Code Analysis 看不起我

2021-02-12 14:34 UTC, Polar-Pumpkin requested changes
不要强暴我的 Repo

2021-02-12 14:34 UTC, Polar-Pumpkin commented on src/main/java/org/serverct/parrot/parrotx/PPlugin.java
> +                }
我 (今天刚想到) 认为不应该在配置文件指定bStats Plugin ID, 因为这样用户可以修改 ID 导致刷了半天的数据贡献给了别家明星 (?). 应该提供一个 PPlugin protected 方法设置 Plugin ID

2021-02-12 14:34 UTC, Polar-Pumpkin commented on src/main/java/org/serverct/parrot/parrotx/data/autoload/register/ExpansionRegister.java
> +}
你自己说的有问题, 问题是什么, 修好了吗?

2021-02-12 14:37 UTC, closed without merging